name: thunder
description: "Flutter network inspector for Dio client, offering real-time monitoring, detailed logs, and curl command generation for debugging."
version: 1.0.2-dev.6

homepage: https://github.com/Miracle-Blue/thunder
repository: https://github.com/Miracle-Blue/thunder
issue_tracker: https://github.com/Miracle-Blue/thunder/issues

topics:
  - network
  - debugging
  - inspection
  - http

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
